[boot]
systemd=false
command="bash /wsl2_command_init"

[network]
generateHosts=true
generateResolvConf=true
hostname="noonomyen_wsl"

[interop]
enabled=true
appendWindowsPath=true

[user]
default="noonomyen"

